//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Компания.EmotionsLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "EmotionsLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"EmotionsLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Компания";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID EmotionsLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EmotionsLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID EmotionsLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EmotionsLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewEmotionsLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EmotionsLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string EmotionsLanguagePackageId = "07c03dca-eafa-43b2-a0b9-5774ec2a6ea9";
		
		// Editor factory identifier
		public const string EmotionsLanguageEditorFactoryId = "fce59e12-731f-4268-a23a-a8d5b11ba88b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string EmotionsLanguageModelExplorerToolWindowId = "5f5548ae-89e2-4c8d-a956-11f748abd4af";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Компания.EmotionsLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string EmotionsLanguageCommandSetId = "43786c81-f823-4c28-a3d1-48aa1938025a";
	}
}